sudo: false

language: node_js

notifications:
  email: false

node_js:
  - stable

cache:
  directories:
    - node_modules

before_script:
  - npm prune

script:
  - npm run lint
  - npm run test
  - npm run test:acceptance

after_success:
  - npm run codecov
  - npm run release

branches:
  only:
    - master
    - /^greenkeeper/.*$/
