sudo: false

language: node_js

notifications:
  email: false

node_js:
- stable

cache:
  directories:
  - node_modules

script:
- npm run flow
- npm run storybook:test
- npm run test:coverage
- npm run build

after_success:
- node_modules/.bin/codecov
- npm run release

branches:
  only:
  - master
